import './globals.css'
// google-font
import { Rubik } from 'next/font/google'
const rubik = Rubik({ subsets: ['latin'] })
// components
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Create Next.JS App',
  description: 'Generated by create next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
